// js/data.js

const batteryData = [
  {
    id: "1",
    model: "Solar-50",
    plates: 5,
    boxSize: "NS-40",
    weightKg: 5.1,
    dimensions: { l: "7.72", w: "5.08", h: "7.95", unit: "in" },
    ah: 22,
    p: 12,
    warranty: "None",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/solar/s50.png",
    categories: ["Solar"],
    uses: "Home UPS, Solar Inverters",
  },
  {
    id: "2",
    series: "dry-charge",
    model: "A 55L",
    plates: 7,
    boxSize: "NS-40",
    weightKg: 6.54,
    dimensions: { l: "7.72", w: "5.08", h: "7.95", unit: "in" },
    ah: 32,
    p: 12,
    warranty: "6 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/automotive/a55.png",
    categories: ["Automotive"], // Fixed filters
    uses: ["Small Hatchbacks, Generators"], // Updated uses
  },
  {
    id: "3",
    model: "A 60L/R",
    plates: 9,
    boxSize: "NS-40",
    weightKg: 7.69,
    dimensions: { l: "7.72", w: "5.08", h: "7.95", unit: "in" },
    ah: 42,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/automotive/a60.png",
    categories: ["Automotive"],
    uses: ["Small Hatchbacks, Generators"],
  },
  {
    id: "4",
    model: "A 65L",
    plates: 11,
    boxSize: "NS-40",
    weightKg: 8.98,
    dimensions: { l: "7.72", w: "5.08", h: "7.95", unit: "in" },
    ah: 50,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/automotive/a65.png",
    categories: ["Automotive"],
    uses: "Small Hatchbacks, Generators",
  },
  {
    id: "5",
    model: "A 70L/R",
    plates: 11,
    boxSize: "N-40",
    weightKg: 8.65,
    dimensions: { l: "9.13", w: "5.08", h: "7.95", unit: "in" },
    ah: 50,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/automotive/a70.png",
    categories: ["Automotive"],
    uses: "Small Hatchbacks, Generators",
  },
  {
    id: "6",
    model: "A 75L/R",
    plates: 13,
    boxSize: "N-40",
    weightKg: 9.82,
    dimensions: { l: "9.13", w: "5.08", h: "7.95", unit: "in" },
    ah: 55,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/automotive/a75.png",
    categories: ["Automotive"],
    uses: "Small Hatchbacks, Generators",
  },
  {
    id: "7",
    model: "A 90",
    plates: 9,
    boxSize: "N-50",
    weightKg: 9.8,
    dimensions: { l: "10.08", w: "6.69", h: "7.95", unit: "in" },
    ah: 50,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/automotive/a90.png",
    categories: ["Automotive"],
    uses: "Small Hatchbacks, Generators",
  },
  {
    id: "8",
    model: "A 95Z/ZL",
    plates: 11,
    boxSize: "N-50",
    weightKg: 11.1,
    dimensions: { l: "10.08", w: "6.69", h: "7.95", unit: "in" },
    ah: 60,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/automotive/a95.png",
    categories: ["Automotive"],
    uses: "Small Hatchbacks, Generators",
  },
  {
    id: "9",
    model: "A 99",
    plates: 21,
    boxSize: "N-50",
    weightKg: 11.1,
    dimensions: { l: "10.08", w: "6.69", h: "7.95", unit: "in" },
    ah: 65,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/automotive/a99.png",
    categories: ["Automotive"],
    uses: "UPS Backup, Solar Inverters",
  },
  {
    id: "10",
    model: "Solar-100",
    plates: 9,
    boxSize: "N-70",
    weightKg: 10.42,
    dimensions: { l: "11.65", w: "6.61", h: "7.95", unit: "in" },
    ah: 60,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/solar/s100.png",
    categories: ["Solar"],
    uses: "Home UPS, Solar Inverters,Off-Grid Home Systems",
  },
  {
    id: "11",
    model: "A 110",
    plates: 11,
    boxSize: "N-70",
    weightKg: 11.99,
    dimensions: { l: "11.65", w: "6.61", h: "7.95", unit: "in" },
    ah: 72,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/automotive/a110.png",
    categories: ["Automotive"],
    uses: "Small Hatchbacks, Generators",
  },
  {
    id: "12",
    model: "A 115Z/ZL",
    plates: 13,
    boxSize: "N-70",
    weightKg: 13.4,
    dimensions: { l: "11.65", w: "6.61", h: "7.95", unit: "in" },
    ah: 80,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/automotive/a115.png",
    categories: ["Automotive", "Solar"],
    uses: "Generators, Solar Inverters",
  },
  {
    id: "13",
    model: "A 120Z/ZL",
    plates: 15,
    boxSize: "N-70",
    weightKg: 14.9,
    dimensions: { l: "11.65", w: "6.61", h: "7.95", unit: "in" },
    ah: 85,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/automotive/a120.png",
    categories: ["Automotive", "Solar"],
    uses: "Generators, Solar Inverters",
  },
  {
    id: "14",
    model: "A 130",
    plates: 15,
    boxSize: "6X15",
    weightKg: 16,
    dimensions: { l: "14.45", w: "6.69", h: "7.95", unit: "in" },
    ah: 100,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/solar/s130.png",
    categories: ["Solar"],
    uses: "Home UPS, Solar Inverters,Off-Grid Home Systems",
  },
  {
    id: "15",
    model: "A 140",
    plates: 17,
    boxSize: "6X15",
    weightKg: 17.66,
    dimensions: { l: "14.45", w: "6.69", h: "7.95", unit: "in" },
    ah: 105,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/solar/s140.png",
    categories: ["Solar"],
    uses: "Home UPS, Solar Inverters,Off-Grid Home Systems",
  },
  {
    id: "16",
    model: "A 150",
    plates: 17,
    boxSize: "N-100",
    weightKg: 18.78,
    dimensions: { l: "14.96", w: "6.77", h: "8.07", unit: "in" },
    ah: 110,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/solar/s150.png",
    categories: ["Solar", "Industrial"],
    uses: "Home UPS, Solar Inverters,Agricultural Machinery",
  },
  {
    id: "17",
    model: "A 160",
    plates: 19,
    boxSize: "N-100",
    weightKg: 19.64,
    dimensions: { l: "14.96", w: "6.77", h: "8.07", unit: "in" },
    ah: 115,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/solar/s160.png",
    categories: ["Solar", "Industrial"],
    uses: "Home UPS, Solar Inverters,Agricultural Machinery",
  },
  {
    id: "18",
    model: "A 180",
    plates: 19,
    boxSize: "N-120",
    weightKg: 22.2,
    dimensions: { l: "19.69", w: "7.01", h: "8.27", unit: "in" },
    ah: 120,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/industrial/a180.png",
    categories: ["Industrial"],
    uses: "Agricultural Machinery, Heavy Vehicles,Heavy Machinery Backup",
  },
  {
    id: "19",
    model: "A 200",
    plates: 21,
    boxSize: "N-120",
    weightKg: 24.4,
    dimensions: { l: "19.69", w: "7.01", h: "8.27", unit: "in" },
    ah: 130,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/industrial/a200.png",
    categories: ["Industrial"],
    uses: "Agricultural Machinery, Heavy Vehicles,Heavy Machinery Backup",
  },
  {
    id: "20",
    model: "A 205",
    plates: 23,
    boxSize: "N-120",
    weightKg: 26.0,
    dimensions: { l: "19.69", w: "7.01", h: "8.27", unit: "in" },
    ah: 140,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/industrial/a205.png",
    categories: ["Industrial"],
    uses: "Agricultural Machinery, Heavy Vehicles,Heavy Machinery Backup",
  },
  {
    id: "21",
    model: "A 210",
    plates: 21,
    boxSize: "N-150",
    weightKg: 26.01,
    dimensions: { l: "19.76", w: "8.58", h: "8.27", unit: "in" },
    ah: 135,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/industrial/a210.png",
    categories: ["Industrial"],
    uses: "Agricultural Machinery, Heavy Vehicles,Heavy Machinery Backup",
  },
  {
    id: "22",
    model: "A 230",
    plates: 23,
    boxSize: "N-150",
    weightKg: 27.7,
    dimensions: { l: "19.76", w: "8.58", h: "8.27", unit: "in" },
    ah: 150,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/industrial/a230.png",
    categories: ["Industrial"],
    uses: "Agricultural Machinery, Heavy Vehicles,Heavy Machinery Backup",
  },
  {
    id: "23",
    model: "A 260",
    plates: 25,
    boxSize: "N-150",
    weightKg: 28.28,
    dimensions: { l: "19.76", w: "8.58", h: "8.27", unit: "in" },
    ah: 160,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/industrial/a260.png",
    categories: ["Industrial"],
    uses: "Agricultural Machinery, Heavy Vehicles,Heavy Machinery Backup",
  },
  {
    id: "24",
    model: "A 270",
    plates: 27,
    boxSize: "N-150",
    weightKg: 30.25,
    dimensions: { l: "19.76", w: "8.58", h: "8.27", unit: "in" },
    ah: 180,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/industrial/a270.png",
    categories: ["Industrial"],
    uses: "Agricultural Machinery, Heavy Vehicles,Heavy Machinery Backup",
  },
  {
    id: "25",
    model: "A 280",
    plates: 31,
    boxSize: "N-200",
    weightKg: 34.5,
    dimensions: { l: "20.28", w: "10.8", h: "8.27", unit: "in" },
    ah: 210,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/industrial/a280.png",
    categories: ["Industrial"],
    uses: "Agricultural Machinery, Heavy Vehicles,Heavy Machinery Backup",
  },
  {
    id: "26",
    model: "A 290",
    plates: 33,
    boxSize: "N-200",
    weightKg: 36.4,
    dimensions: { l: "20.28", w: "10.8", h: "8.27", unit: "in" },
    ah: 210,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/industrial/a290.png",
    categories: ["Industrial"],
    uses: "Agricultural Machinery, Heavy Vehicles,Heavy Machinery Backup",
  },
  {
    id: "101",
    series: "deep-cycle",
    model: "DC 1100",
    plates: 11,
    boxSize: "N-70",
    weightKg: 13.85,
    dimensions: { l: "11.65", w: "6.61", h: "7.95", unit: "in" },
    ah: 80,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/deep-cycle/dc1100.png",
    categories: ["Deep-Cycle"],
    uses: "UPS Backup, Solar Inverters",
  },
  {
    id: "102",
    series: "deep-cycle",
    model: "DC 1600",
    plates: 19,
    boxSize: "N-120",
    weightKg: 22.45,
    dimensions: { l: "19.69", w: "7.01", h: "8.27", unit: "in" },
    ah: 130,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/deep-cycle/dc1600.png",
    categories: ["Deep-Cycle"],
    uses: "UPS Backup, Solar Inverters",
  },
  {
    id: "103",
    series: "deep-cycle",
    model: "DC 2000",
    plates: 21,
    boxSize: "N-150",
    weightKg: 0,
    dimensions: { l: "19.76", w: "8.58", h: "8.27", unit: "in" },
    ah: 160,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/deep-cycle/dc2000.png",
    categories: ["Deep-Cycle"],
    uses: "UPS Backup, Solar Inverters",
  },
  {
    id: "201",
    series: "mf",
    model: "MF 50",
    plates: 5,
    boxSize: "",
    weightKg: 0,
    dimensions: { l: "", w: "", h: "", unit: "in" },
    ah: 22,
    p: 12,
    warranty: "None",
    tech: "German Engineering Maintenance Free Battery",
    image: "assets/batteries/mf/mf-50.png",
    categories: ["Automotive"],
    uses: "660cc - 1000cc Vehicles",
  },
  {
    id: "202",
    series: "mf",
    model: "MF 55",
    plates: 7,
    boxSize: "",
    weightKg: 0,
    dimensions: { l: "", w: "", h: "", unit: "in" },
    ah: 34,
    p: 12,
    warranty: "6 Months",
    tech: "German Engineering Maintenance Free Battery",
    image: "assets/batteries/mf/mf-55.png",
    categories: ["Automotive"],
    uses: "660cc - 1000cc Vehicles",
  },
  {
    id: "203",
    series: "mf",
    model: "MF 60L",
    plates: 9,
    boxSize: "",
    weightKg: 0,
    dimensions: { l: "", w: "", h: "", unit: "in" },
    ah: 42,
    p: 12,
    warranty: "15 Months",
    tech: "German Engineering Maintenance Free Battery",
    image: "assets/batteries/mf/mf-60L.png",
    categories: ["Automotive"],
    uses: "800cc - 1300cc Vehicles",
  },
  {
    id: "204",
    series: "mf",
    model: "MF 60R",
    plates: 9,
    boxSize: "",
    weightKg: 0,
    dimensions: { l: "", w: "", h: "", unit: "in" },
    ah: 42,
    p: 12,
    warranty: "15 Months",
    tech: "German Engineering Maintenance Free Battery",
    image: "assets/batteries/mf/mf-60R.png",
    categories: ["Automotive"],
    uses: "800cc - 1300cc Vehicles",
  },
  {
    id: "205",
    series: "mf",
    model: "MF 70L",
    plates: 11,
    boxSize: "",
    weightKg: 0,
    dimensions: { l: "", w: "", h: "", unit: "in" },
    ah: 50,
    p: 12,
    warranty: "15 Months",
    tech: "German Engineering Maintenance Free Battery",
    image: "assets/batteries/mf/mf-70L.png",
    categories: ["Automotive"],
    uses: "1300cc - 1800cc Vehicles",
  },
];

// Helper function to get products by series
const getProductsBySeries = (seriesName) => {
  return batteryData.filter((item) => item.series === seriesName);
};
